config/routes.rb
Vishnoo::Application.routes.draw do

  devise_for :users

  resources :posts

  root :to => 'welcome#index'

  match "gallery" => 'welcome#gallery', via: :get

  match "tributes" => 'welcome#tributes', via: :get

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    # if a member, they can manage their own posts
    # (or create new ones)
    if user.role? :member
      can :manage, Post, :user_id => user.id
      can :manage, Comment, :user_id => user.id
    end

    # Moderators can delete any post
    if user.role? :moderator
      can :destroy, Post
      can :destroy, Comment
    end

    # Admins can do anything
    if user.role? :admin
      can :manage, :all
    end

    can :read, :all
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
  	attr_accessible :body, :title, :image

  default_scope order('created_at DESC')

  mount_uploader :image, ImageUploader

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :avatar
  # attr_accessible :title, :body
  has_many :posts

  before_create :set_member

  mount_uploader :avatar, AvatarUploader

  ROLES = %w[member moderator admin]
	def role?(base_role)
	  role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
	end

	private

	  def set_member
	    self.role = 'member'
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def new
  	@post = Post.new
    authorize! :create, Post, message: "You need to be a member to create a new post."
  end

  def create
    @post = current_user.posts.build(params[:post])
    authorize! :create, @post, message: "You need to be signed up to do that."
  if @post.save
    flash[:notice] = "Post was saved."
    redirect_to @post
  else
    flash[:error] = "There was an error saving the post. Please try again."
    render :new
  end
end

  def edit
    @post = Post.find(params[:id])
    authorize! :edit, @post, message: "You need to own the post to edit it."
  end

  def update
    @post = Post.find(params[:id])
    authorize! :update, @post, message: "You need to own the post to edit it."
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was updated."
      redirect_to @post
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def gallery
  end

  def tributes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def control_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'control-group error'
    else
      content_tag :div, capture(&block), class: 'control-group'
    end
  end

  def markdown(text)
	  renderer = Redcarpet::Render::HTML.new
	  extensions = {fenced_code_blocks: true}
	  redcarpet = Redcarpet::Markdown.new(renderer, extensions)
	  (redcarpet.render text).html_safe
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vishnoo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<script type="text/javascript">
  $(document).ready(function() {
  $("a.fancybox-button").fancybox({
    prevEffect    : 'none',
    nextEffect    : 'none',
    closeBtn    : true,
    helpers   : {
      title : { type : 'inside' },
      buttons : {}
    }
  });
});
</script>



</head>
<body>
  <div class="container">
    <div class="row">
      <div class="span12">
        <ul class="nav nav-tabs">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Tributes", posts_path %></li>
          <li><%= link_to "Gallery", gallery_path %></li>

          <div class="pull-right user-info">
            <% if current_user %>
              <%= image_tag(current_user.avatar.tiny.url, class: "img-rounded") if current_user.avatar? %>
            Bonjour <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %> or
              <%= link_to "Sign Up", new_user_registration_path %>
            <% end %>
          </div>
        </ul>

        <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

    <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for [post], html: { class: 'form-horizontal' } do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-block">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= control_group_tag(post.errors[:title]) do %>
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  <% end %>
  <%= control_group_tag(post.errors[:body]) do %>
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, rows: 8 %>
    </div>
  <% end %>
  <div class="control-group">
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Save", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Tribute</h1>
<div class="row">
  <div class="span4">
    <p>Guidelines for editing tributes:</p>
    <ul>
      <li>Edit the title.</li>
      <li>Edit your tribute.</li>
      <li>Upload an image.</li>
      <li>Submit your tribute.</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { post: @post } %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>All Tributes</h1>
  <% if can? :create, Post %>
    <%= link_to "New Tribute", new_post_path, class: 'btn btn-large' %>
    <br>
  <% end %>
    <div class="container">
      <div class="row">
        <br>
        <% @posts.each do |post| %>
          <div class="span3">
            <div>
              <p><%= image_tag(post.image_url, class: "img-rounded") %></p>
              <h4><strong><%= link_to post.title, post_path(post) %></strong></h4>
              <br>
            </div>
          </div>
          <% end %>
          <br>
        </div>
        <br>
      </div>

app/views/posts/new.html.erb
<h1>New Tribute</h1>

<div class="row">
  <div class="span4">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Choose a title.</li>
      <li>Write your tribute.</li>
      <li>Upload an image.</li>
      <li>Submit your tribute.</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= markdown @post.title %></h1>

<div class="row">
  <div class="span8">
    <small>
      <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by
      <%= @post.user.name %>
    </small>
    <p><%= markdown @post.body %></p>
    <small>
      <%= image_tag(@post.image.thumb.url, class: "img-rounded") %>
    </small>
  </div>
  <div class="span4">
    <% if can? :edit, @post %>
      <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-large btn-block' %>
    <% end %>
    <%= link_to "Back to Tributes", posts_path, class: 'btn btn-large btn-block' %>
  </div>
</div>

app/views/welcome/gallery.html.erb
<div class="container">
  <div class="row">
    <div class="span3">
      <%= link_to image_tag("vishnoo1.jpeg", class: "img-rounded"), asset_path("vishnoo1.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "The Boy" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo9.jpeg", class: "img-rounded"), asset_path("vishnoo9.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "The Young Man" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo3.jpeg", class: "img-rounded"), asset_path("vishnoo3.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo4.jpeg", class: "img-rounded"), asset_path("vishnoo4.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="span3">
      <%= link_to image_tag("vishnoo25.jpeg", class: "img-rounded"), asset_path("vishnoo5.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo6.jpeg", class: "img-rounded"), asset_path("vishnoo6.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo7.jpeg", class: "img-rounded"), asset_path("vishnoo7.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo8.jpeg", class: "img-rounded"), asset_path("vishnoo8.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
     </div>
   </div>
   <br>
   <div class="row">
    <div class="span3">
      <%= link_to image_tag("vishnoo2.jpeg", class: "img-rounded"), asset_path("vishnoo2.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo10.jpeg", class: "img-rounded"), asset_path("vishnoo10.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo11.jpeg", class: "img-rounded"), asset_path("vishnoo11.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo12.jpeg", class: "img-rounded"), asset_path("vishnoo12.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="span3">
      <%= link_to image_tag("vishnoo13.jpeg", class: "img-rounded"), asset_path("vishnoo13.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
    </div>
    <div class="span3">
      <%= link_to image_tag("vishnoo14.jpeg", class: "img-rounded"), asset_path("vishnoo14.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
     </div>
     <div class="span3">
      <%= link_to image_tag("vishnoo15.jpeg", class: "img-rounded"), asset_path("vishnoo15.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
      </div>
      <div class="span3">
        <%= link_to image_tag("vishnoo16.jpeg", class: "img-rounded"), asset_path("vishnoo16.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
       </div>
     </div>
     <br>
     <div class="row">
       <div class="span3">
        <%= link_to image_tag("vishnoo17.jpeg", class: "img-rounded"), asset_path("vishnoo17.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
       </div>
      <div class="span3">
        <%= link_to image_tag("vishnoo18.jpeg", class: "img-rounded"), asset_path("vishnoo18.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
      </div>
      <div class="span3">
        <%= link_to image_tag("vishnoo19.jpeg", class: "img-rounded"), asset_path("vishnoo19.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
      </div>
      <div class="span3">
        <%= link_to image_tag("vishnoo20.jpeg", class: "img-rounded"), asset_path("vishnoo20.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="span3">
        <%= link_to image_tag("vishnoo21.jpeg", class: "img-rounded"), asset_path("vishnoo21.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
      </div>
      <div class="span3">
        <%= link_to image_tag("vishnoo22.jpeg", class: "img-rounded"), asset_path("vishnoo22.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
      </div>
      <div class="span3">
        <%= link_to image_tag("vishnoo23.jpeg", class: "img-rounded"), asset_path("vishnoo23.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
      </div>
      <div class="span3">
        <%= link_to image_tag("vishnoo24.jpeg", class: "img-rounded"), asset_path("vishnoo24.jpeg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
      </div>
    </div>
    <br>
    <br>
    <br>

app/views/welcome/index.html.erb
<center>
<h1>In Memory of Vishnoo Paupiah</h1>
<br>
<p><%= image_tag("vishnoo22.jpeg", class: "img-rounded") %></p>
<br>
<h2>7th February 1951 - 26th December 2013</h2>
<h3>Beloved Father, Brother, Uncle & Friend </h3>

app/views/welcome/tributes.html.erb
<h1>Welcome#tributes</h1>
<p>Find me in app/views/welcome/tributes.html.erb</p>